//
// Created by theom on 26/11/2023.
//

/* TROUVER UN MOYEN DE RESOUDRE LES CONTRAINTES DE PRECEDENCE ET DE TEMPS, EN GARDANT UN NOMBRE DE STATIONS MINIMAL ET EN RESPECTANT LES CONTRAINTES DE TEMPS
  SIMON FAIS DES RECHERCHES */
